@Library('my-jenkins-shared-library') _


pipeline {
     agent any
    // { label 'final-iti-project' }
     environment {
        USERNAME        = 'abdo23'
        PASSWORD        = 'Abdo@01287306586'
        DOCKER_REGISTRY = 'abdo23'
        DOCKER_IMAGE    = 'final-project-iti'
        BUILD_NUMBER    = '1'
        BUILD_PATH      = './deploy-with-jenkins-slave'
     }
    stages {
        stage('build') {
            steps {
                echo 'build'
                script{
                     buildAndPush(
                         USERNAME: env.USERNAME,
                         PASSWORD: env.PASSWORD,
                         DOCKER_REGISTRY: env.DOCKER_REGISTRY,
                         DOCKER_IMAGE: env.DOCKER_IMAGE,
                         BUILD_NUMBER: env.BUILD_NUMBER,
                         BUILD_PATH: env.BUILD_PATH
                     ) 
                                // withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                                //     sh '''
                                        
                                //         docker login -u ${USERNAME} -p ${PASSWORD}
                                //         // docker build -t abdo23/final-project-iti:v${BUILD_NUMBER} ./deploy-with-jenkins-slave
                                //         buildAndPush(DOCKER_REGISTRY: env.DOCKER_REGISTRY, DOCKER_IMAGE: env.DOCKER_IMAGE, BUILD_NUMBER: env.BUILD_NUMBER)

                                //         // docker push abdo23/final-project-iti:v${BUILD_NUMBER}
                                //         echo ${BUILD_NUMBER} > ../build.txt
                                        
                                //     '''
                              
                    // }
                }
            }
        }
        stage('deploy') {
            steps {
                echo 'deploy'
                script {
                         sh " echo succeeded " 
                                // withCredentials([file(credentialsId: 'kubeconfig-credentials', variable: 'KUBECONFIG1'),
                                //                  file(credentialsId: 'key-gke-file', variable: 'KUBECONFIG')]) {
                                //     sh '''
                                //         export BUILD_NUMBER=$(cat ../build.txt)
                                //         mv Deployment/deploy.yaml Deployment/deploy.yaml.tmp
                                //         cat Deployment/deploy.yaml.tmp | envsubst > Deployment/deploy.yaml
                                //         rm -f Deployment/deploy.yaml.tmp
                                //          gcloud auth activate-service-account controling-gke@iti-gcp-abdo.iam.gserviceaccount.com  --key-file=${KUBECONFIG}
                                //         gcloud container clusters get-credentials my-gke-project  --zone us-central1-a --project iti-gcp-abdo
                                //         kubectl apply -f Deployment --kubeconfig ${KUBECONFIG1} 
                                //     '''
                                // }
                         }
                    }
                }
          
    }
}
