pipeline {
     agent any
    // { label 'final-iti-project' }
     environment {
        DOCKER_REGISTRY = 'docker.io/abdo23'
        DOCKER_IMAGE = 'new-app-project'
        SERVER_NAME = 'https://api.ocpuat.devopsconsulting.org:6443'
        OPENSHIFT_TOKEN = 'sha256~2WTzYAScmhdm7sYQtPRuHx-4ZsuliaN2FGr4FDaNxq0'
        OPENSHIFT_PROJECT = 'abdelrahman'
        SONARQUBE_TOKEN = '11986ba88cfe1b603256e331f33d03679486adc0'
        SONARQUBE_PROJECTKEY = 'ivlove-project'
    }
    stages {
        stage('build') {
            steps {
                echo 'build'
                script{
                        
                                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                                    sh '''
                                        docker login -u ${USERNAME} -p ${PASSWORD}
                                        // docker build -t abdo23/final-project-iti:v${BUILD_NUMBER} ./deploy-with-jenkins-slave
                                        buildAndPush(DOCKER_REGISTRY: env.DOCKER_REGISTRY, DOCKER_IMAGE: env.DOCKER_IMAGE, BUILD_NUMBER: env.BUILD_NUMBER)

                                        // docker push abdo23/final-project-iti:v${BUILD_NUMBER}
                                        echo ${BUILD_NUMBER} > ../build.txt
                                        
                                    '''
                              
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                echo 'deploy'
                script {
                         sh " echo succeeded " 
                                // withCredentials([file(credentialsId: 'kubeconfig-credentials', variable: 'KUBECONFIG1'),
                                //                  file(credentialsId: 'key-gke-file', variable: 'KUBECONFIG')]) {
                                //     sh '''
                                //         export BUILD_NUMBER=$(cat ../build.txt)
                                //         mv Deployment/deploy.yaml Deployment/deploy.yaml.tmp
                                //         cat Deployment/deploy.yaml.tmp | envsubst > Deployment/deploy.yaml
                                //         rm -f Deployment/deploy.yaml.tmp
                                //          gcloud auth activate-service-account controling-gke@iti-gcp-abdo.iam.gserviceaccount.com  --key-file=${KUBECONFIG}
                                //         gcloud container clusters get-credentials my-gke-project  --zone us-central1-a --project iti-gcp-abdo
                                //         kubectl apply -f Deployment --kubeconfig ${KUBECONFIG1} 
                                //     '''
                                // }
                         }
                    }
                }
          
    }
}
